# GitHub Actions workflow for building and releasing the Discord Notification Feed
# Triggers on:
# - Push to main/master
# - Tags with v prefix (releases)
# - Pull requests to main/master
# - Manual workflow dispatch

name: Build Electron App

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      forceBuild:
        description: 'Force build regardless of changes'
        required: false
        default: 'false'
        type: boolean

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    # Build matrix for cross-platform compilation
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        
    steps:
    # Checkout repository
    - uses: actions/checkout@v3
    
    # Setup Node.js environment with caching
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    # Install project dependencies
    - name: Install dependencies
      run: npm ci
      
    # Build application
    - name: Build
      run: npm run build
      
    # Package app and publish if this is a tag
    - name: Package and Publish Electron App
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        if [[ "${{ github.ref }}" == refs/tags/* ]]; then
          npm run publish
        else
          npm run package
        fi
      shell: bash
      
    # Upload build artifacts for non-release builds
    - name: Upload artifacts
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ runner.os }}-build
        path: dist/**/*
